use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use tauri::{AppHandle, Emitter, Manager, State};
use tokio_util::sync::CancellationToken;

use super::client::{self, StreamOutcome};
use super::types::{ChatRequest, ChatRole};
use crate::chats::store::ChatsStore;
use crate::chats::titles;
use crate::chats::types::ActiveGeneration;
use crate::providers::store::Store;

/// Everything the backend knows about a running generation.
#[derive(Clone)]
pub struct GenerationRecord {
	pub cancel: CancellationToken,
	pub chat_id: String,
	/// Full content text streamed so far.
	pub accumulated: Arc<Mutex<String>>,
	/// Reasoning tokens (extended thinking) streamed so far.
	pub reasoning: Arc<Mutex<String>>,
}

/// requestId -> record for every running generation.
pub type GenerationsState = Mutex<HashMap<String, GenerationRecord>>;

/// Runs after the stream completes (by any path) — persists the assistant
/// message and bumps the chat. Title generation is spawned off separately so
/// it never delays the `chat://done` event. Removing the record *before*
/// emitting closes the F5-restore race.
async fn finalize_generation(
	app: &AppHandle,
	request_id: &str,
	chat_id: &str,
	text: &str,
	reasoning: &str,
	failed: bool,
) {
	let now = chrono_millis();
	let mut needs_title = false;

	// Sync: persist the assistant message and touch the chat.
	{
		let state = app.try_state::<Mutex<ChatsStore>>();
		if let Some(state) = state {
			if let Ok(store) = state.lock() {
				if !text.is_empty() || !reasoning.is_empty() {
					let _ = store.append_message(
						&titles::new_id(),
						chat_id,
						"assistant",
						text,
						Some(reasoning),
						now,
					);
				}
				let _ = store.touch_chat(chat_id, now);
				needs_title = store
					.chat_exists(chat_id)
					.ok()
					.unwrap_or(false)
					&& store
						.list_chats()
						.ok()
						.and_then(|chats| {
							chats
								.iter()
								.find(|c| c.id == chat_id)
								.and_then(|c| c.title.clone())
						})
						.is_none();
			}
		}
	}

	// The first exchange (no title yet) gets an LLM-generated one — in the
	// background, so a slow title never blocks the done event.
	if needs_title && !failed {
		let app = app.clone();
		let chat_id = chat_id.to_string();
		tauri::async_runtime::spawn(async move {
			let source = {
				let state = app.try_state::<Mutex<ChatsStore>>();
				let source = state.and_then(|s| {
					s.lock().ok().and_then(|store| {
						store.first_user_message(&chat_id).ok().flatten()
					})
				});
				source
			};
			if let Some(source) = source {
				// LLM titles can fail (network, rate limits) or come back
				// empty — a derived fallback keeps every chat named.
				let title = generate_chat_title(&app, &source)
					.await
					.unwrap_or_else(|| titles::ChatTitleRequest::fallback_title(&source));
				let state = app.try_state::<Mutex<ChatsStore>>();
				if let Some(state) = state {
					if let Ok(store) = state.lock() {
						let _ = store.rename_chat(&chat_id, &title);
					}
				}
				// Let the sidebar pick up the new title immediately.
				let _ = app.emit(
					super::client::CHATS_UPDATED_EVENT,
					serde_json::json!({ "chatId": chat_id }),
				);
			}
		});
	}

	// Remove from the registry BEFORE emitting, so a reload that lands
	// between the save and the event still sees a finished generation.
	{
		let state = app.try_state::<GenerationsState>();
		if let Some(state) = state {
			if let Ok(mut map) = state.lock() {
				map.remove(request_id);
			}
		}
	}
}

/// Fire-and-forget title generation against the chat's own provider.
async fn generate_chat_title(app: &AppHandle, source: &str) -> Option<String> {
	// All lock-guarded reads finish before any await, keeping the future Send.
	let (base_url, api_key, model_id) = {
		let state = app.try_state::<Mutex<Store>>()?;
		let store = state.lock().ok()?;
		let data = &store.data;
		let active = data.active_model.clone()?;
		let provider = data
			.providers
			.iter()
			.find(|p| p.id == active.provider_id)?;
		(
			provider.base_url.clone(),
			provider.api_key.clone(),
			active.model_id,
		)
	};
	titles::generate_title(
		Some(app),
		&base_url,
		&api_key,
		&titles::ChatTitleRequest {
			provider_id: String::new(),
			model_id,
			source: source.to_string(),
		},
	)
	.await
	.ok()
}

fn chrono_millis() -> i64 {
	std::time::SystemTime::now()
		.duration_since(std::time::UNIX_EPOCH)
		.map(|d| d.as_millis() as i64)
		.unwrap_or(0)
}

/// Starts a streaming chat completion. The `requestId` is generated by the
/// frontend and passed in, so early `chat://delta` events can never race
/// the invoke result. The user message is persisted before the task spawns;
/// the assistant message is saved by the task on completion (including
/// partial text when stopped). Deltas arrive via `chat://delta`, completion
/// via `chat://done`, failures/stops via `chat://error`.
#[tauri::command]
pub async fn start_chat(
	app: AppHandle,
	generations: State<'_, GenerationsState>,
	chats: State<'_, Mutex<ChatsStore>>,
	request: ChatRequest,
	request_id: String,
	chat_id: String,
) -> Result<String, String> {
	let user_message = request
		.messages
		.last()
		.filter(|m| m.role == ChatRole::User)
		.map(|m| m.content.clone())
		.ok_or_else(|| "Request must end with a user message".to_string())?;

	// Persist the user message up front — visible even if the app closes
	// mid-generation. The chat row is created by the frontend beforehand.
	// Edit/regenerate flows pass `persistUser: false` (the message is
	// already in the DB; only the tail was truncated).
	{
		let store = chats.lock().map_err(|e| e.to_string())?;
		if !store.chat_exists(&chat_id)? {
			return Err("Chat not found".to_string());
		}
		if request.persist_user.unwrap_or(true) {
			store.append_message(
				&titles::new_id(),
				&chat_id,
				"user",
				&user_message,
				None,
				chrono_millis(),
			)?;
		}
	}

	let record = GenerationRecord {
		cancel: CancellationToken::new(),
		chat_id: chat_id.clone(),
		accumulated: Arc::new(Mutex::new(String::new())),
		reasoning: Arc::new(Mutex::new(String::new())),
	};
	generations
		.lock()
		.map_err(|e| e.to_string())?
		.insert(request_id.clone(), record.clone());

	let messages = request.messages.clone();
	let run_id = request_id.clone();

	tauri::async_runtime::spawn(async move {
		let outcome = client::stream_chat(
			&app,
			&run_id,
			&request,
			&messages,
			&record,
		)
		.await;
		let text = record.acccumulated_text();
		let reasoning = record.reasoning_text();
		match outcome {
			Ok(StreamOutcome::Done(usage)) => {
				finalize_generation(&app, &run_id, &chat_id, &text, &reasoning, false)
					.await;
				client::emit_done(&app, &run_id, usage);
			}
			Ok(StreamOutcome::Cancelled) => {
				finalize_generation(&app, &run_id, &chat_id, &text, &reasoning, false)
					.await;
				client::emit_error(&app, &run_id, "Generation stopped".to_string(), true);
			}
			Err(message) => {
				finalize_generation(&app, &run_id, &chat_id, &text, &reasoning, true)
					.await;
				client::emit_error(&app, &run_id, message, false);
			}
		}
	});

	Ok(request_id)
}

/// Stops a running generation by its `requestId`.
#[tauri::command]
pub fn stop_chat(
	app: AppHandle,
	generations: State<'_, GenerationsState>,
	request_id: String,
) -> Result<bool, String> {
	let map = generations.lock().map_err(|e| e.to_string())?;
	Ok(match map.get(&request_id) {
		Some(record) => {
			record.cancel.cancel();
			crate::logging::info(
				&app,
				"chat",
				"Generation stopped by user",
				Some(serde_json::json!({ "requestId": request_id })),
			);
			true
		}
		None => false,
	})
}

/// Snapshot of the running generation, if any. Used on app start / reload
/// to restore the streaming state.
#[tauri::command]
pub fn get_active_generation(
	generations: State<'_, GenerationsState>,
) -> Result<Option<ActiveGeneration>, String> {
	let map = generations.lock().map_err(|e| e.to_string())?;
	Ok(map
		.iter()
		.next()
		.map(|(request_id, record)| ActiveGeneration {
			request_id: request_id.clone(),
			chat_id: record.chat_id.clone(),
			text: record.acccumulated_text(),
			reasoning: record.reasoning_text(),
		}))
}

impl GenerationRecord {
	pub fn acccumulated_text(&self) -> String {
		self.locked_clone(&self.accumulated)
	}

	pub fn reasoning_text(&self) -> String {
		self.locked_clone(&self.reasoning)
	}

	fn locked_clone(&self, buffer: &Arc<Mutex<String>>) -> String {
		buffer.lock().map(|text| text.clone()).unwrap_or_default()
	}
}
